# Redirect all Terraform references to our fork.
#[[override]]
#  name = "github.com/terraform-providers/terraform-provider-aws"
#  source = "github.com/pulumi/terraform-provider-aws"
#  branch = "pulumi-master"
#
#[[override]]
#  name = "github.com/terraform-providers/terraform-provider-azurerm"
#  source = "github.com/pulumi/terraform-provider-azurerm"
#  branch = "pulumi-master"

[[override]]
  name = "github.com/masterzen/azure-sdk-for-go"
  branch = "master"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  branch = "master"

[[override]]
  name = "github.com/ugorji/go"
  revision = "d463ef40929c1805e71d5e821ac82f6b90cbc7c6"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"
