name: release
on:
  push:
    tags: [ "v*" ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.14.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.132.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Chocolatey Package Deployment
        run: |
          CURRENT_TAG=v$(pulumictl get version --language generic -o)
          pulumictl create choco-deploy -a tf2pulumi v${CURRENT_TAG}

